// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: inference.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []*Image               `protobuf:"bytes,1,rep,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictBatchRequest) Reset() {
	*x = PredictBatchRequest{}
	mi := &file_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictBatchRequest) ProtoMessage() {}

func (x *PredictBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictBatchRequest.ProtoReflect.Descriptor instead.
func (*PredictBatchRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{0}
}

func (x *PredictBatchRequest) GetImage() []*Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pixels        []float32              `protobuf:"fixed32,1,rep,packed,name=pixels,proto3" json:"pixels,omitempty"` // length must equal the models input_dim
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{1}
}

func (x *Image) GetPixels() []float32 {
	if x != nil {
		return x.Pixels
	}
	return nil
}

type Prediction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PredictedClass int32                  `protobuf:"varint,1,opt,name=predicted_class,json=predictedClass,proto3" json:"predicted_class,omitempty"`
	Confidence     float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Prediction) Reset() {
	*x = Prediction{}
	mi := &file_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prediction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prediction) ProtoMessage() {}

func (x *Prediction) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prediction.ProtoReflect.Descriptor instead.
func (*Prediction) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{2}
}

func (x *Prediction) GetPredictedClass() int32 {
	if x != nil {
		return x.PredictedClass
	}
	return 0
}

func (x *Prediction) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type PredictBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Predictions   []*Prediction          `protobuf:"bytes,1,rep,name=predictions,proto3" json:"predictions,omitempty"` // same order/length as the request
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictBatchResponse) Reset() {
	*x = PredictBatchResponse{}
	mi := &file_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictBatchResponse) ProtoMessage() {}

func (x *PredictBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictBatchResponse.ProtoReflect.Descriptor instead.
func (*PredictBatchResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{3}
}

func (x *PredictBatchResponse) GetPredictions() []*Prediction {
	if x != nil {
		return x.Predictions
	}
	return nil
}

var File_inference_proto protoreflect.FileDescriptor

const file_inference_proto_rawDesc = "" +
	"\n" +
	"\x0finference.proto\x12\tinference\"=\n" +
	"\x13PredictBatchRequest\x12&\n" +
	"\x05image\x18\x01 \x03(\v2\x10.inference.ImageR\x05image\"\x1f\n" +
	"\x05Image\x12\x16\n" +
	"\x06pixels\x18\x01 \x03(\x02R\x06pixels\"U\n" +
	"\n" +
	"Prediction\x12'\n" +
	"\x0fpredicted_class\x18\x01 \x01(\x05R\x0epredictedClass\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\"O\n" +
	"\x14PredictBatchResponse\x127\n" +
	"\vpredictions\x18\x01 \x03(\v2\x15.inference.PredictionR\vpredictions2b\n" +
	"\x0fInferenceEngine\x12O\n" +
	"\fPredictBatch\x12\x1e.inference.PredictBatchRequest\x1a\x1f.inference.PredictBatchResponseB8Z6mini-inference-serving-system/go-server/internal/pb;pbb\x06proto3"

var (
	file_inference_proto_rawDescOnce sync.Once
	file_inference_proto_rawDescData []byte
)

func file_inference_proto_rawDescGZIP() []byte {
	file_inference_proto_rawDescOnce.Do(func() {
		file_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)))
	})
	return file_inference_proto_rawDescData
}

var file_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_inference_proto_goTypes = []any{
	(*PredictBatchRequest)(nil),  // 0: inference.PredictBatchRequest
	(*Image)(nil),                // 1: inference.Image
	(*Prediction)(nil),           // 2: inference.Prediction
	(*PredictBatchResponse)(nil), // 3: inference.PredictBatchResponse
}
var file_inference_proto_depIdxs = []int32{
	1, // 0: inference.PredictBatchRequest.image:type_name -> inference.Image
	2, // 1: inference.PredictBatchResponse.predictions:type_name -> inference.Prediction
	0, // 2: inference.InferenceEngine.PredictBatch:input_type -> inference.PredictBatchRequest
	3, // 3: inference.InferenceEngine.PredictBatch:output_type -> inference.PredictBatchResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_inference_proto_init() }
func file_inference_proto_init() {
	if File_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_proto_goTypes,
		DependencyIndexes: file_inference_proto_depIdxs,
		MessageInfos:      file_inference_proto_msgTypes,
	}.Build()
	File_inference_proto = out.File
	file_inference_proto_goTypes = nil
	file_inference_proto_depIdxs = nil
}
